### ISSUE TITLE
Need system requirement

### ISSUE THREAD

**Issue by peter279k** [ace411/couchdb_ext#1]
In `README`, it lacks the `System requirement` section.

After looking at the `install.sh` file, it seems that this project uses the `Ubutnu 16.04`?

**Comment by ace411** [comment]
That's accurate. I haven't tested it on other platforms yet.

**Comment by peter279k** [comment]
I add the `documentation` tag because it's important for developers to build this extension.

**Comment by ace411** [comment]
https://github.com/ace411/couchdb_ext/pull/4
