### ISSUE TITLE
The error new of line

### ISSUE THREAD

**Issue by peter279k** [ace411/couchdb_ext#2]
It looks like the new line of file is the `CRLF` (`\r\n`), not `LF` (`\n`).

I think it should be the `LF`(`\n`).

**Comment by ace411** [comment]
I have two questions:

1. In which file(s) is this most salient?
2. What are the performance implications in regard to the PHP userland?

**Comment by peter279k** [comment]
@ace411, thank you for your reply.

It should organize coding style and the `\n` is the new line on `Linux-like` system.

And the `Windows` system is `\r\n`.

**Comment by ace411** [comment]
https://github.com/ace411/couchdb_ext/pull/4
