### ISSUE TITLE
Publish to PECL

### ISSUE THREAD

**Issue by tuaris** [ace411/couchdb_ext#7]
Have you considered publishing this to https://pecl.php.net/

**Comment by ace411** [comment]
I have, Mr. Morante. I'll ask Derrick Rethans to give me access to the platform. Also, I appreciate the enthusiasm you are showing regarding the project.

**Comment by ace411** [comment]
I recently got my PECL account request approved. This extension will soon be a part of PECL.

**Comment by martijn80** [comment]
Hi, did you got around publishing on pecl?
I like to try this extension but couldnt find at (now deprecated) pecl.php.net

Did you know about the new way? Its called pie and its a composer for extensions.

More info:
-  https://packagist.org/extensions
- https://github.com/php/pie/blob/1.4.x/docs/extension-maintainers.md
