### ISSUE TITLE
Consider dropping .docker folder

### ISSUE THREAD

**Issue by peter279k** [ace411/couchdb_ext#9]
IMHO, I think it should be good to split Docker image build environment from `couchdb_ext` repository.

They're different. One is about development environment and another one is PHP extension development repository.

I've created the Docker image build environment on this [repository](https://github.com/peter279k/docker_couchdb_ext).

And it will be published latest image via GitHub action on upcoming commits :).

@ace411, what do you think about this :)?

**Comment by ace411** [comment]
I deleted the `.docker` folder. Thanks for the input.

**Comment by peter279k** [comment]
@ace411, thanks for your reply.

I also think you can mention Docker build environment on `README` :).

And it can be easy for developers to know the development environment with Docker support!
